INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('AF', 'AFGHANISTAN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('AL', 'ALBANIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('DZ', 'ALGERIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('AS', 'AMERICAN SAMOA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('AD', 'ANDORRA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('AO', 'ANGOLA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('AI', 'ANGUILLA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('AQ', 'ANTARCTICA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('AG', 'ANTIGUA AND BARBUDA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('AR', 'ARGENTINA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('AM', 'ARMENIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('AW', 'ARUBA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('AU', 'AUSTRALIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('AT', 'AUSTRIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('AZ', 'AZERBAIJAN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BS', 'BAHAMAS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BH', 'BAHRAIN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BD', 'BANGLADESH');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BB', 'BARBADOS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BY', 'BELARUS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BE', 'BELGIUM');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BZ', 'BELIZE');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BJ', 'BENIN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BM', 'BERMUDA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BT', 'BHUTAN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BO', 'BOLIVIA, PLURINATIONAL STATE OF');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BA', 'BOSNIA AND HERZEGOVINA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BW', 'BOTSWANA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BV', 'BOUVET ISLAND');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BR', 'BRAZIL');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('IO', 'BRITISH INDIAN OCEAN TERRITORY');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BN', 'BRUNEI DARUSSALAM');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BG', 'BULGARIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BF', 'BURKINA FASO');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BI', 'BURUNDI');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('KH', 'CAMBODIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('CM', 'CAMEROON');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('CA', 'CANADA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('CV', 'CAPE VERDE');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('KY', 'CAYMAN ISLANDS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('CF', 'CENTRAL AFRICAN REPUBLIC');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('TD', 'CHAD');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('CL', 'CHILE');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('CN', 'CHINA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('CX', 'CHRISTMAS ISLAND');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('CC', 'COCOS (KEELING) ISLANDS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('CO', 'COLOMBIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('KM', 'COMOROS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('CG', 'CONGO');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('CK', 'COOK ISLANDS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('CR', 'COSTA RICA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('CI', 'CÔTE DIVOIRE');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('HR', 'CROATIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('CU', 'CUBA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('CY', 'CYPRUS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('CZ', 'CZECH REPUBLIC');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('DK', 'DENMARK');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('DJ', 'DJIBOUTI');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('DM', 'DOMINICA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('DO', 'DOMINICAN REPUBLIC');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('EC', 'ECUADOR');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('EG', 'EGYPT');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('SV', 'EL SALVADOR');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('GQ', 'EQUATORIAL GUINEA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('ER', 'ERITREA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('EE', 'ESTONIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('ET', 'ETHIOPIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('FK', 'FALKLAND ISLANDS (MALVINAS)');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('FO', 'FAROE ISLANDS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('FJ', 'FIJI');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('FI', 'FINLAND');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('FR', 'FRANCE');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('GF', 'FRENCH GUIANA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('PF', 'FRENCH POLYNESIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('TF', 'FRENCH SOUTHERN TERRITORIES');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('GA', 'GABON');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('GM', 'GAMBIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('GE', 'GEORGIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('DE', 'GERMANY');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('GH', 'GHANA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('GI', 'GIBRALTAR');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('GR', 'GREECE');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('GL', 'GREENLAND');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('GD', 'GRENADA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('GP', 'GUADELOUPE');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('GU', 'GUAM');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('GT', 'GUATEMALA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('GG', 'GUERNSEY');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('GN', 'GUINEA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('GW', 'GUINEA-BISSAU');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('GY', 'GUYANA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('HT', 'HAITI');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('HM', 'HEARD ISLAND AND MCDONALD ISLANDS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('VA', 'HOLY SEE (VATICAN CITY STATE)');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('HN', 'HONDURAS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('HK', 'HONG KONG');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('HU', 'HUNGARY');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('IS', 'ICELAND');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('IN', 'INDIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('ID', 'INDONESIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('IR', 'IRAN, ISLAMIC REPUBLIC OF');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('IQ', 'IRAQ');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('IE', 'IRELAND');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('IM', 'ISLE OF MAN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('IL', 'ISRAEL');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('IT', 'ITALY');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('JM', 'JAMAICA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('JP', 'JAPAN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('JE', 'JERSEY');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('JO', 'JORDAN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('KZ', 'KAZAKHSTAN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('KE', 'KENYA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('KI', 'KIRIBATI');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('KP', 'KOREA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('KR', 'KOREA, REPUBLIC OF');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('KW', 'KUWAIT');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('KG', 'KYRGYZSTAN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('LA', 'LAO');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('LV', 'LATVIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('LB', 'LEBANON');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('LS', 'LESOTHO');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('LR', 'LIBERIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('LY', 'LIBYAN ARAB JAMAHIRIYA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('LI', 'LIECHTENSTEIN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('LT', 'LITHUANIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('LU', 'LUXEMBOURG');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MO', 'MACAO');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MG', 'MADAGASCAR');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MW', 'MALAWI');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MY', 'MALAYSIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MV', 'MALDIVES');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('ML', 'MALI');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MT', 'MALTA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MH', 'MARSHALL ISLANDS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MQ', 'MARTINIQUE');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MR', 'MAURITANIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MU', 'MAURITIUS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('YT', 'MAYOTTE');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MX', 'MEXICO');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('FM', 'MICRONESIA, FEDERATED STATES OF');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MD', 'MOLDOVA, REPUBLIC OF');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MC', 'MONACO');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MN', 'MONGOLIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('ME', 'MONTENEGRO');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MS', 'MONTSERRAT');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MA', 'MOROCCO');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MZ', 'MOZAMBIQUE');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MM', 'MYANMAR');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('NA', 'NAMIBIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('NR', 'NAURU');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('NP', 'NEPAL');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('NL', 'NETHERLANDS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('AN', 'NETHERLANDS ANTILLES');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('NC', 'NEW CALEDONIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('NZ', 'NEW ZEALAND');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('NI', 'NICARAGUA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('NE', 'NIGER');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('NG', 'NIGERIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('NU', 'NIUE');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('NF', 'NORFOLK ISLAND');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MP', 'NORTHERN MARIANA ISLANDS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('NO', 'NORWAY');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('OM', 'OMAN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('PK', 'PAKISTAN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('PW', 'PALAU');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('PS', 'PALESTINIAN TERRITORY, OCCUPIED');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('PA', 'PANAMA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('PG', 'PAPUA NEW GUINEA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('PY', 'PARAGUAY');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('PE', 'PERU');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('PH', 'PHILIPPINES');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('PN', 'PITCAIRN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('PL', 'POLAND');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('PT', 'PORTUGAL');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('PR', 'PUERTO RICO');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('QA', 'QATAR');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('RE', 'RÉUNION');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('RO', 'ROMANIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('RU', 'RUSSIAN FEDERATION');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('RW', 'RWANDA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('BL', 'SAINT BARTHÉLEMY');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('SH', 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('KN', 'SAINT KITTS AND NEVIS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('LC', 'SAINT LUCIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('MF', 'SAINT MARTIN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('PM', 'SAINT PIERRE AND MIQUELON');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('VC', 'SAINT VINCENT AND THE GRENADINES');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('WS', 'SAMOA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('SM', 'SAN MARINO');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('ST', 'SAO TOME AND PRINCIPE');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('SA', 'SAUDI ARABIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('SN', 'SENEGAL');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('RS', 'SERBIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('SC', 'SEYCHELLES');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('SL', 'SIERRA LEONE');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('SG', 'SINGAPORE');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('SK', 'SLOVAKIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('SI', 'SLOVENIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('SB', 'SOLOMON ISLANDS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('SO', 'SOMALIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('ZA', 'SOUTH AFRICA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('ES', 'SPAIN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('LK', 'SRI LANKA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('SD', 'SUDAN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('SR', 'SURINAME');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('SJ', 'SVALBARD AND JAN MAYEN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('SZ', 'SWAZILAND');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('SE', 'SWEDEN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('CH', 'SWITZERLAND');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('SY', 'SYRIAN ARAB REPUBLIC');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('TW', 'TAIWAN, PROVINCE OF CHINA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('TJ', 'TAJIKISTAN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('TZ', 'TANZANIA, UNITED REPUBLIC OF');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('TH', 'THAILAND');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('TL', 'TIMOR-LESTE');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('TG', 'TOGO');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('TK', 'TOKELAU');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('TO', 'TONGA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('TT', 'TRINIDAD AND TOBAGO');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('TN', 'TUNISIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('TR', 'TURKEY');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('TM', 'TURKMENISTAN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('TC', 'TURKS AND CAICOS ISLANDS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('TV', 'TUVALU');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('UG', 'UGANDA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('UA', 'UKRAINE');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('AE', 'UNITED ARAB EMIRATES');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('GB', 'UNITED KINGDOM');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('US', 'UNITED STATES');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('UM', 'UNITED STATES MINOR OUTLYING ISLANDS');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('UY', 'URUGUAY');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('UZ', 'UZBEKISTAN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('VU', 'VANUATU');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('VE', 'VENEZUELA, BOLIVARIAN REPUBLIC OF');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('VN', 'VIET NAM');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('VG', 'VIRGIN ISLANDS, BRITISH');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('VI', 'VIRGIN ISLANDS, U.S.');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('WF', 'WALLIS AND FUTUNA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('EH', 'WESTERN SAHARA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('YE', 'YEMEN');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('ZM', 'ZAMBIA');
INSERT INTO flightagent_countrymodels (isocode, name) VALUES ('ZW', 'ZIMBABWE');